[package]
name = "cocopy"
authors = ["Johan Geluk"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
stderrlog = "0.5"
log = "0.4"
itertools = "0.10"
clap = { features = ["derive"], version = "4.0"}